version: '3.9'
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: docker
    ports:
      - '26018:27017'

  api:
    container_name: api-container
    build: .
    restart: always
    image: clean-ts-api
    command: npm start
    volumes:
      - ./dist:/usr/src/clean-ts-api/dist
    ports:
      - '5050:5050'
    links: 
      - mongo
